jms_serializer:
    default_context:
        serialization:
            serialize_null: true
    visitors:
        json_serialization:
            options:
                - JSON_UNESCAPED_SLASHES
                - JSON_PRESERVE_ZERO_FRACTION
